### ISSUE TITLE
Can't get stuff from Mouser (Error 500 when requesting a component)

### ISSUE THREAD

**Issue by joelvonrotz** [Part-DB/Part-DB-symfony#550]
Hello,
I'm currently evaluating PartDB with its KiCAD integration and I'm happy so far. But I've got one issue: I can't request anything from Mouser via the "Create parts from info provider" menu. When I look for a component for example _K220J15C0GF53H5_, I get the error 500.

![image](https://github.com/Part-DB/Part-DB-server/assets/41155337/cfd95b83-7fed-4a07-9243-b2ee5137ed91)

My docker compose looks as following (with the key censored):

```yaml
version: '3.3'
services:
  partdb:
    container_name: partdb
    # By default Part-DB will be running under Port 8080, you can change it here
    ports:
      - '8080:80'
    volumes:
      # By default
      - ./uploads:/var/www/html/uploads
      - ./public_media:/var/www/html/public/media
      - ./db:/var/www/html/var/db
    restart: unless-stopped
    image: jbtronics/part-db1:latest
    environment:
      # Put SQLite database in our mapped folder. You can configure some other kind of database here too.
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/db/app.db
      # In docker env logs will be redirected to stderr
      - APP_ENV=docker

      # You can configure Part-DB using environment variables
      # Below you can find the most essential ones predefined
      # However you can add any other environment configuration you want here
      # See .env file for all available options or https://docs.part-db.de/configuration.html
      # !!! Do not use quotes around the values, as they will be interpreted as part of the value and this will lead to errors !!!

      # The language to use serverwide as default (en, de, ru, etc.)
      - DEFAULT_LANG=en
      # The default timezone to use serverwide (e.g. Europe/Berlin)
      - DEFAULT_TIMEZONE=Europe/Zurich
      # The currency that is used inside the DB (and is assumed when no currency is set). This can not be changed later, so be sure to set it the currency used in your country
      - BASE_CURRENCY=CHF
      # The name of this installation. This will be shown as title in the browser and in the header of the website
      - INSTANCE_NAME=Part-DB

      # Allow users to download attachments to the server by providing an URL
      # This could be a potential security issue, as the user can retrieve any file the server has access to (via internet)
      - ALLOW_ATTACHMENT_DOWNLOADS=0
      # Use gravatars for user avatars, when user has no own avatar defined
      - USE_GRAVATAR=1

      # Override value if you want to show a given text on homepage.
      # When this is empty the content of config/banner.md is used as banner
      - BANNER=Joel's part database

      # Mouser API
      - PROVIDER_MOUSER_KEY=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
      - PROVIDER_MOUSER_SEARCH_OPTION='InStock'
    
      # If you use a reverse proxy in front of Part-DB, you must configure the trusted proxies IP addresses here (see reverse proxy documentation for more information):
      # - TRUSTED_PROXIES=127.0.0.0/8,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16  
```

And these are the server information:

![image](https://github.com/Part-DB/Part-DB-server/assets/41155337/c684fc70-0e06-4015-8f3a-ebca7c8294a5)

![image](https://github.com/Part-DB/Part-DB-server/assets/41155337/03dfa638-716b-464b-b963-f00815c939c1)

![image](https://github.com/Part-DB/Part-DB-server/assets/41155337/cdff09e8-a4ba-47ec-a723-a82236c8987b)

Did I do something dumb?
